import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import AuthWrapper from "./auth_wrapper";
import { Session } from "inspector";
import { SessionProvider } from "next-auth/react";
import { auth } from '@/auth'
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  console.log(session)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session} >
          {children}
        </SessionProvider>

      </body>
    </html>
  );
}
